[colors.bright]
black = "0x4c4c4c"
blue = "#00A8FF"
cyan = "#3EC9D0"
green = "#2CD257"
magenta = "#9681C2"
red = "#CD5162"
white = "0xf5f5f5"
yellow = "#9CB1D8"

[colors.normal]
black = "0x262626"
blue = "#50B3E5"
cyan = "#63C1C5"
green = "#2CD257"
magenta = "#9681C2"
red = "#D72C43"
white = "0xe7e7e7"
yellow = "#718fc8"

[colors.primary]
background = "#000000"
foreground = "0xf0f0f0"

[cursor.style]
shape = "Beam"

[font]
size = 10

[font.bold]
family = "Mononoki NerdFont"
style = "Bold"

[font.italic]
family = "Mononoki NerdFont"
style = "Bold Italic"

[font.normal]
family = "Mononoki NerdFont"
style = "Bold"

[window]
opacity = 0.85

[window.padding]
x = 2
y = 2
