colors:
  primary:
    background: '#000000'
    foreground: '0xf0f0f0'

  normal:
    black:   '0x262626'
    red:     '#d16271'
    green:   '#68b999'
    yellow:  '#718fc8'
    blue:    '#98cee9'
    magenta: '#9681C2'
    cyan:    '#7DA9AB'
    white:   '0xe7e7e7'
    orange:  '0xc6a679' #Here for reference

  bright:
    black:   '0x4c4c4c'
    red:     '#CC7F8A'
    green:   '0x9ec49f'
    yellow:  '#9CB1D8'
    blue:    '0xa39ec4'
    magenta: '0xc49ec4'
    cyan:    '0x9ec3c4'
    white:   '0xf5f5f5'
    orange:  '0xceb188'

font:
  bold:
    family: Mononoki NerdFont
    style: Bold
  italic:
    family: Mononoki NerdFont
    style: Bold Italic
  normal:
    family: Mononoki NerdFont
    style: Bold
  size: 10

window:
  opacity: 0.85
  padding:
    x: 0
    y: 0

cursor:
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Beam

    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    #blinking: Off
